### ISSUE TITLE
Consider using DOMHighResTimestamp instead of DOMTimeStamp

### ISSUE THREAD

**Issue by yoavweiss** [WICG/handwriting-recognition#24]
We're considering our options RE `DOMTimeStamp`, and wondering what it's used for. It seems less well-defined than `DOMHighResTimestamp`. Would y'all consider switching over?

See heycam/webidl#2 for discussion.

**Comment by wacky6** [comment]
We use DOMTimeStamp to tell the writing order of each point / stroke (which is written first), and to tell (roughly) the writing speed of a stroke.

Doesn't matter if it's absolute or relative. The API only require the time (`t` in HandwritingStroke.addPoint) is measured in the same way for a given HandwritingDrawing.

Based on the definition, I think `DOMTimeStamp` and `DOMHighResTimestamp` are interchangable for this API.

**Comment by yoavweiss** [comment]
Thanks! I'd appreciate it if y'all could switch over :)

**Comment by wacky6** [comment]
Fixed inhttps://github.com/WICG/handwriting-recognition/pull/25

Updated the IDL to use DOMHighResTimestamp.
