### ISSUE TITLE
Handling confusable characters

### ISSUE THREAD

**Issue by r12a** [WICG/handwriting-recognition#5]
https://github.com/WICG/handwriting-recognition/blob/main/explainer.md#the-prediction-result

> The prediction result may contain (if the implementation choose to support):

> alternatives: A list of JavaScript objects, where each object has a text field. These are the next best predictions (alternatives), in decreasing confidence order. Up to a maximum of alternatives (given in hints) strings. For example, the first string is the second best prediction (the best being the prediction result).

I suspect that for some languages the may will be a must, since many orthographies use the same glyphs to represent more than one semantic, eg. some use letters as numbers, some have indistinguishable glyphs for different underlying code points or sequences (eg. par excellence Mongolian, but also many others), and some have glyph shapes that can be ambiguous if not drawn carefully because the differences are very small.

The model may not require alternatives for certain languages, but should not preclude them for others (which may not yet be supported).

**Comment by wacky6** [comment]
Are you suggesting we make `alternatives` mandatory (in return value)?

We aren't percluding `alternatives` from a explainer/standard's perspective, and we certainly do hope browsers implement this attribute. We didn't mandate this because we are unsure if all recognizers supports it. 

This aside, from a web developer's stand point. They always have the choice to check for feature support before using this API.

```JavaScript
if (language === "a language that must have alternatives" \
    && navigator.queryHandwritingRecognizerSupport('alternatives)) {
    // Do handwriting recognition
} else {
    // Handwriting not supported.
}
```

**Comment by wacky6** [comment]
We've changed to a new query API. The new API returns a description of the recognizer.

`alternative` (`textAlternative` in the new query API) is now mandatory in the return value. Web applications can simply check if the recognizer returns alternatives before using it.

Closing.
